# Generated by Django 5.0.1 on 2026-02-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='メッセージID')),
                ('thread_id', models.CharField(db_index=True, max_length=255, verbose_name='スレッドID')),
                ('from_address', models.EmailField(max_length=255, verbose_name='送信元')),
                ('to_address', models.EmailField(max_length=255, verbose_name='宛先')),
                ('subject', models.CharField(max_length=500, verbose_name='件名')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='受信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('snippet', models.TextField(blank=True, null=True, verbose_name='スニペット')),
                ('body_text', models.TextField(blank=True, null=True, verbose_name='本文（テキスト）')),
                ('body_html', models.TextField(blank=True, null=True, verbose_name='本文（HTML）')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='Gmail API レスポンス')),
            ],
            options={
                'verbose_name': 'Gmailメッセージ',
                'verbose_name_plural': 'Gmailメッセージ',
                'db_table': 'gmail_messages',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='idx_received_at')],
            },
        ),
    ]
