# Generated by Django 5.0.1 on 2026-02-06 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAssessmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='お申込番号')),
                ('application_datetime', models.DateTimeField(verbose_name='お申込日時')),
                ('desired_sale_timing', models.CharField(blank=True, max_length=100, verbose_name='希望売却時期')),
                ('maker', models.CharField(blank=True, max_length=100, verbose_name='メーカー名')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='車種名')),
                ('year', models.CharField(blank=True, max_length=100, verbose_name='年式')),
                ('mileage', models.CharField(blank=True, max_length=100, verbose_name='走行距離')),
                ('customer_name', models.CharField(max_length=100, verbose_name='お名前')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('gmail_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_assessments', to='leads.gmailmessage', verbose_name='元メッセージ')),
            ],
            options={
                'verbose_name': '車査定申込',
                'verbose_name_plural': '車査定申込',
                'db_table': 'car_assessment_requests',
                'ordering': ['-application_datetime'],
                'indexes': [models.Index(fields=['-application_datetime'], name='idx_app_datetime'), models.Index(fields=['customer_name'], name='idx_customer_name'), models.Index(fields=['phone_number'], name='idx_phone_number')],
            },
        ),
    ]
