# Generated by Django 5.0.1 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_carassessmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='carassessmentrequest',
            name='follow_status',
            field=models.CharField(choices=[('未対応', '未対応'), ('不通', '不通'), ('再コール予定', '再コール予定'), ('商談アポ獲得', '商談アポ獲得'), ('成約', '成約'), ('見送り', '見送り')], default='未対応', max_length=30, verbose_name='対応ステータス'),
        ),
        migrations.AddField(
            model_name='carassessmentrequest',
            name='sales_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='担当確定日時'),
        ),
        migrations.AddField(
            model_name='carassessmentrequest',
            name='sales_note',
            field=models.TextField(blank=True, default='', verbose_name='対応コメント'),
        ),
        migrations.AddField(
            model_name='carassessmentrequest',
            name='sales_owner_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='担当営業'),
        ),
        migrations.AddField(
            model_name='carassessmentrequest',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ステータス更新日時'),
        ),
        migrations.AddField(
            model_name='carassessmentrequest',
            name='status_updated_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='ステータス更新者'),
        ),
    ]
