# Generated by Django 5.0.1 on 2026-04-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_documenttypemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(max_length=50, verbose_name='連番種別')),
                ('key', models.CharField(max_length=100, verbose_name='キー')),
                ('last_seq', models.PositiveIntegerField(default=0, verbose_name='最終連番')),
            ],
            options={
                'verbose_name': '連番管理',
                'verbose_name_plural': '連番管理',
                'db_table': 'number_sequences',
                'unique_together': {('sequence_type', 'key')},
            },
        ),
    ]
