# Generated by Django 5.0.1 on 2026-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_numbersequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='総合評価（1〜5、0.5刻み）'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('in_progress', '査定中'), ('contracted', '成約'), ('lost', '没'), ('pre_cancel', '査定前キャンセル'), ('managed', '管理')], default='in_progress', max_length=20, verbose_name='ステータス'),
        ),
    ]
