# Generated by Django 5.0.1 on 2026-04-14 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_overall_rating_decimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontract',
            name='correction_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='金額訂正承認日時'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='correction_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='金額訂正承認者（社長）'),
        ),
    ]
