# Generated by Django 5.0.1 on 2026-04-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_contract_correction_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='免許証番号'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='document_handover_date',
            field=models.DateField(blank=True, null=True, verbose_name='書類引渡日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='recycle_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='リサイクル券金額①'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='vehicle_handover_date',
            field=models.DateField(blank=True, null=True, verbose_name='車両引渡日'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='ボディタイプ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='駆動方式'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='passenger_count',
            field=models.CharField(blank=True, max_length=5, verbose_name='乗車定員'),
        ),
    ]
