# Generated by Django 5.0.1 on 2026-04-16 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_contract_print_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontract',
            name='automobile_tax_unpaid',
            field=models.BooleanField(blank=True, null=True, verbose_name='自動車税未納'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='flood_hail_damage',
            field=models.BooleanField(blank=True, null=True, verbose_name='冠水車・雹害'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='invoice_registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='適格請求書登録番号'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='malfunction',
            field=models.BooleanField(blank=True, null=True, verbose_name='故障箇所'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='manager1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts_1', to=settings.AUTH_USER_MODEL, verbose_name='責任者1'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='manager2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts_2', to=settings.AUTH_USER_MODEL, verbose_name='責任者2'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='meter_tampering',
            field=models.BooleanField(blank=True, null=True, verbose_name='メーター戻し・改ざん等'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='parking_violation',
            field=models.BooleanField(blank=True, null=True, verbose_name='駐車違反放置反則金未納'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='qualified_invoice_registered',
            field=models.BooleanField(blank=True, null=True, verbose_name='適格請求書発行事業者登録'),
        ),
    ]
