# Generated by Django 5.0.1 on 2026-04-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_contract_vehicle_status_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='インボイス登録番号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_taxable_business',
            field=models.BooleanField(blank=True, null=True, verbose_name='課税事業者'),
        ),
    ]
