# Generated by Django 5.0.1 on 2026-04-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_customer_taxable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='furigana',
            field=models.CharField(blank=True, max_length=100, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='customerbankaccount',
            name='bank_institution_type',
            field=models.CharField(choices=[('bank', '銀行'), ('shinkin', '信用金庫'), ('nokyo', '農協'), ('yucho', 'ゆうちょ')], default='bank', max_length=20, verbose_name='金融機関種別'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'ガソリン'), ('diesel', 'ディーゼル'), ('hybrid', 'ハイブリッド（HV）'), ('phev', 'プラグインハイブリッド（PHEV）'), ('ev', '電気自動車（EV）'), ('lpg', 'LPG'), ('other', 'その他')], max_length=20, verbose_name='燃料種別'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='型式'),
        ),
    ]
