# Generated by Django 5.0.1 on 2026-04-22 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_add_furigana_modeltype_fueltype_institutiontype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carassessmentrequest',
            name='external_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='外部ステータス'),
        ),
        migrations.AddField(
            model_name='carassessmentrequest',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終スクレイピング日時'),
        ),
        migrations.AddConstraint(
            model_name='carassessmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('external_service_id', ''), _negated=True), fields=('channel_type', 'external_service_id'), name='uq_channel_external_id'),
        ),
    ]
