# Generated by Django 5.0.1 on 2026-04-22 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_add_external_status_scraped_at_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carassessmentrequest',
            name='uq_channel_external_id',
        ),
        migrations.AddIndex(
            model_name='carassessmentrequest',
            index=models.Index(fields=['channel_type', 'external_service_id'], name='idx_channel_external_id'),
        ),
    ]
