# Generated by Django 5.0.1 on 2026-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_rename_appointment_status_to_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontract',
            name='ininjyo_received',
            field=models.BooleanField(default=False, verbose_name='委任状 受取済'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='inkan_received',
            field=models.BooleanField(default=False, verbose_name='印鑑証明 受取済'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='jotohyo_received',
            field=models.BooleanField(default=False, verbose_name='除票 受取済'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='jotosho_received',
            field=models.BooleanField(default=False, verbose_name='譲渡書 受取済'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='juminhyo_received',
            field=models.BooleanField(default=False, verbose_name='住民票 受取済'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='kanpu_received',
            field=models.BooleanField(default=False, verbose_name='還付 受取済'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='required_ininjyo_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='委任状（通数）'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='required_inkan_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='印鑑証明（通数）'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='required_jotohyo_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='除票（通数）'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='required_jotosho_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='譲渡書（通数）'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='required_juminhyo_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='住民票（通数）'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='required_kanpu_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='還付（通数）'),
        ),
    ]
