# Generated by Django 5.0.1 on 2026-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_add_required_docs_to_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='first_registration_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='repair_history_flag',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transmission_type',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_system_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='査定システムID'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_system_imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='査定システム取込日時'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_system_recycle_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='リサイクル券金額（査定システム取込）'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='repair_history_flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='修復歴'),
        ),
    ]
