# Generated by Django 5.0.1 on 2026-05-13 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_normalize_assessment_prices_to_yen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認申請日時'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='approval_requested_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='承認申請先'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認申請日時'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='approval_requested_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='承認申請先'),
        ),
    ]
