# Generated by Django 5.0.1 on 2026-05-14 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_add_approval_request_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_done', models.BooleanField(default=False, verbose_name='書類')),
                ('intake_done', models.BooleanField(default=False, verbose_name='入庫')),
                ('repair_done', models.BooleanField(default=False, verbose_name='加修')),
                ('transport_done', models.BooleanField(default=False, verbose_name='陸送')),
                ('listing_done', models.BooleanField(default=False, verbose_name='出品')),
                ('sale_done', models.BooleanField(default=False, verbose_name='売却')),
                ('payment_done', models.BooleanField(default=False, verbose_name='入金')),
                ('transfer_done', models.BooleanField(default=False, verbose_name='振込')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_process', to='leads.purchasecontract', verbose_name='買取契約')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_processes', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '売掛管理',
                'verbose_name_plural': '売掛管理',
                'db_table': 'sales_processes',
                'ordering': ['contract__assigned_to__last_name', 'contract__contract_date'],
            },
        ),
    ]
