# Generated by Django 5.0.1 on 2026-05-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_add_sales_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprocess',
            name='sold_at',
            field=models.DateField(blank=True, null=True, verbose_name='車両売却日'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='sold_destination',
            field=models.CharField(blank=True, max_length=255, verbose_name='売却先'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='売却金額'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='vehicle_disposition',
            field=models.CharField(blank=True, choices=[('aa', 'AA'), ('display', '展示'), ('loaner', '代車'), ('retail', '販売'), ('scrap', 'ラップ')], max_length=10, verbose_name='区分'),
        ),
    ]
