# Generated by Django 5.0.1 on 2026-05-20 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_add_sales_disposition_and_sold_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprocess',
            name='transfer_approval_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='振込承認申請日時'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='transfer_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='振込承認日時'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='transfer_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approved_processes', to=settings.AUTH_USER_MODEL, verbose_name='振込承認者'),
        ),
    ]
