# Generated by Django 5.0.1 on 2026-05-20 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    DB状態:
      - auction_venues テーブルは既に存在（前回の部分失敗で作成済み）
      - sales_processes.sold_destination_id は varchar(255) のまま残っている
    対処:
      - SeparateDatabaseAndState で DB実態とDjango状態を分離
      - DB側は RunSQL で NULL クリア→型変換→FK追加を行う
      - state側は CreateModel + AlterField でモデル状態を更新
    """

    dependencies = [
        ('leads', '0024_add_transfer_approval_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # auction_venues は既に存在するため CREATE は不要
                # 1) varchar のまま NULL 許容にする（空文字を残したまま型変換不可のため先に許容化）
                migrations.RunSQL(
                    sql="ALTER TABLE sales_processes MODIFY COLUMN sold_destination_id VARCHAR(255) NULL DEFAULT NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # 2) 空文字を NULL にクリア
                migrations.RunSQL(
                    sql="UPDATE sales_processes SET sold_destination_id = NULL WHERE sold_destination_id = '' OR sold_destination_id IS NOT NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # 3) BIGINT に型変換（値はすべて NULL なので安全）
                migrations.RunSQL(
                    sql="ALTER TABLE sales_processes MODIFY COLUMN sold_destination_id BIGINT NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # 4) FK 制約を追加
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE sales_processes
                        ADD CONSTRAINT fk_sp_auction_venue
                            FOREIGN KEY (sold_destination_id)
                            REFERENCES auction_venues(id)
                            ON DELETE SET NULL
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AuctionVenue',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True, verbose_name='会場名')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                    ],
                    options={
                        'verbose_name': 'オークション会場',
                        'verbose_name_plural': 'オークション会場',
                        'db_table': 'auction_venues',
                        'ordering': ['name'],
                    },
                ),
                migrations.AlterField(
                    model_name='salesprocess',
                    name='sold_destination',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sales_processes',
                        to='leads.auctionvenue',
                        verbose_name='売却先（会場）',
                    ),
                ),
            ],
        ),
    ]
