# Generated by Django 5.0.1 on 2026-05-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_add_auction_venue_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionvenue',
            name='contract_fee',
            field=models.DecimalField(decimal_places=0, default=13200, max_digits=10, verbose_name='成約費用（円）'),
        ),
        migrations.AddField(
            model_name='auctionvenue',
            name='entry_fee',
            field=models.DecimalField(decimal_places=0, default=12100, max_digits=10, verbose_name='出品費用（円）'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='other_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='その他費用（円）'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='transport_fee_auction',
            field=models.DecimalField(blank=True, decimal_places=0, default=8800, max_digits=10, null=True, verbose_name='オークション会場搬送費用（円）'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='transport_fee_personal',
            field=models.DecimalField(blank=True, decimal_places=0, default=8800, max_digits=10, null=True, verbose_name='個人宅陸送費用（円）'),
        ),
    ]
