# Generated by Django 5.0.1 on 2026-05-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_add_auction_fees_and_transport_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='managed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='管理開始日時'),
        ),
    ]
