# Generated by Django 5.0.1 on 2026-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_add_managed_at_to_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontract',
            name='ininjyo_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='委任状 受領日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='inkan_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='印鑑証明 受領日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='jotohyo_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='除票 受領日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='jotosho_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='譲渡書 受領日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='juminhyo_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='住民票 受領日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='kanpu_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='還付 受領日'),
        ),
    ]
