# Generated by Django 5.0.1 on 2026-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_add_received_date_to_required_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprocess',
            name='intake_date',
            field=models.DateField(blank=True, null=True, verbose_name='入庫日'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='listing_date',
            field=models.DateField(blank=True, null=True, verbose_name='出品日'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='入金日'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='repair_date',
            field=models.DateField(blank=True, null=True, verbose_name='加修完了日'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='振込日'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='transport_date',
            field=models.DateField(blank=True, null=True, verbose_name='陸送完了日'),
        ),
    ]
