# Generated by Django 5.0.1 on 2026-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_add_step_dates_to_sales_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='case_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='社内管理番号'),
        ),
    ]
