# Generated by Django 5.0.1 on 2026-06-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_add_case_number_to_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecontract',
            name='debt_inquiry_completed',
            field=models.BooleanField(default=False, verbose_name='残債照会完了'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='debt_inquiry_completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='残債照会完了日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='debt_remaining_flag',
            field=models.BooleanField(default=False, verbose_name='残債フラグ'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='debt_repayment_completed',
            field=models.BooleanField(default=False, verbose_name='残債返済完了'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='debt_repayment_completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='残債返済完了日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='ownership_release_completed',
            field=models.BooleanField(default=False, verbose_name='所有権解除完了'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='ownership_release_completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='所有権解除完了日'),
        ),
    ]
