# Generated by Django 5.0.1 on 2026-06-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_add_debt_remaining_and_procedure_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasecontract',
            name='ownership_release_completed',
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='ownership_release_requested_date',
            field=models.DateField(blank=True, null=True, verbose_name='解除申請日'),
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='ownership_release_status',
            field=models.CharField(choices=[('not_started', '未対応'), ('in_progress', '対応中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='所有権解除ステータス'),
        ),
    ]
