# Generated by Django 5.0.1 on 2026-06-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_restructure_ownership_release_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasecontract',
            name='debt_inquiry_completed',
        ),
        migrations.RemoveField(
            model_name='purchasecontract',
            name='debt_inquiry_completed_date',
        ),
        migrations.RemoveField(
            model_name='purchasecontract',
            name='debt_repayment_completed',
        ),
        migrations.RemoveField(
            model_name='purchasecontract',
            name='debt_repayment_completed_date',
        ),
    ]
