# Generated by Django 5.0.1 on 2026-06-30 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_remove_debt_completion_checkboxes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('inkan', '印鑑証明'), ('juminhyo', '住民票'), ('jotohyo', '除票'), ('ininjyo', '委任状'), ('jotosho', '譲渡書'), ('kanpu', '還付'), ('contract_signed', '契約書（署名後）')], max_length=20, verbose_name='書類種別')),
                ('file', models.FileField(upload_to='contract_documents/%Y/%m/', verbose_name='ファイル')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='leads.purchasecontract', verbose_name='買取契約')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contract_files', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '契約書類ファイル',
                'verbose_name_plural': '契約書類ファイル',
                'db_table': 'contract_file_uploads',
                'ordering': ['doc_type', '-uploaded_at'],
            },
        ),
    ]
