# Generated by Django 5.0.1 on 2026-06-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_add_contract_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprocess',
            name='document_done',
            field=models.BooleanField(default=False, verbose_name='契約手続'),
        ),
    ]
