# Generated by Django 5.0.1 on 2026-07-01 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_alter_salesprocess_document_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AASaleImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('listing_screen', '出品画面'), ('flow_screen', '流れ画面'), ('winning_bid_screen', '落札画面')], max_length=30, verbose_name='画像種別')),
                ('file', models.FileField(upload_to='aa_images/%Y/%m/', verbose_name='画像ファイル')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('sales_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa_images', to='leads.salesprocess', verbose_name='売却プロセス')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_aa_images', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': 'AA出品画像',
                'verbose_name_plural': 'AA出品画像',
                'db_table': 'aa_sale_images',
                'ordering': ['image_type', '-uploaded_at'],
            },
        ),
    ]
