# Generated by Django 5.0.1 on 2026-07-01 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_add_aa_sale_image_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('document', '書類作成'), ('listing_sheet', '出品表作成'), ('own_transport', '自社陸送'), ('finishing', '仕上げ'), ('car_wash', '洗車'), ('fuel', '燃料'), ('expressway', '高速'), ('parts', '部品'), ('labor', '工賃')], max_length=20, verbose_name='種別')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='金額（円）')),
                ('receipt_image', models.FileField(blank=True, null=True, upload_to='other_fee_receipts/%Y/%m/', verbose_name='領収書画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_other_fee_items', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('sales_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_fee_items', to='leads.salesprocess', verbose_name='売却プロセス')),
            ],
            options={
                'verbose_name': 'その他費用明細',
                'verbose_name_plural': 'その他費用明細',
                'db_table': 'other_fee_items',
                'ordering': ['created_at'],
            },
        ),
    ]
