# Generated by Django 5.0.1 on 2026-07-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_add_other_fee_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='market_price',
        ),
        migrations.AddField(
            model_name='assessment',
            name='market_price_max',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='市場相場価格（上限）'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='market_price_min',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='市場相場価格（下限）'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='aa_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='AA会場評価点'),
        ),
    ]
