# Generated by Django 5.0.1 on 2026-07-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_market_price_range_aa_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprocess',
            name='aa_score',
            field=models.CharField(blank=True, choices=[('5.0', '5.0'), ('4.5', '4.5'), ('4.0', '4.0'), ('3.5', '3.5'), ('3.0', '3.0'), ('2.5', '2.5'), ('2.0', '2.0'), ('1.5', '1.5'), ('1.0', '1.0'), ('R', 'R')], default='', max_length=5, verbose_name='AA会場評価点'),
        ),
    ]
