# Generated by Django 5.0.1 on 2026-07-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_aa_score_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprocess',
            name='contract_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='成約費用（円）'),
        ),
        migrations.AddField(
            model_name='salesprocess',
            name='entry_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='出品費用（円）'),
        ),
    ]
