# Generated by Django 5.0.1 on 2026-07-01 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0040_add_entry_contract_fee_to_salesprocess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='appointment_getter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gotten_appointments', to=settings.AUTH_USER_MODEL, verbose_name='商談取得者'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='案件担当者'),
        ),
    ]
