# Generated by Django 5.0.1 on 2026-04-09 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TSUKUBA', 'つくば'), ('MITO', '水戸'), ('OYAMA', '小山'), ('UTSUNOMIYA', '宇都宮'), ('CC', 'コンタクトセンター'), ('SUPPORT', 'サポート'), ('HQ', '本社業務')], max_length=20, unique=True, verbose_name='店舗コード')),
                ('name', models.CharField(max_length=50, verbose_name='店舗名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'db_table': 'stores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('general', '一般社員'), ('sub_leader', '次席'), ('manager', 'マネージャー'), ('superuser', '全権限')], default='general', max_length=20, verbose_name='ロール')),
                ('employee_number', models.CharField(blank=True, max_length=20, verbose_name='社員番号')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='在籍中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(blank=True, help_text='全権限ロールの場合はNULL', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.store', verbose_name='所属店舗')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
                'db_table': 'user_profiles',
            },
        ),
    ]
