# Generated by Django 5.0.1 on 2026-04-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_store_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '社員情報', 'verbose_name_plural': '社員情報'},
        ),
    ]
