# Generated by Django 5.0.1 on 2026-06-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='社員番号'),
        ),
    ]
